### ISSUE TITLE
Don't work perfectly on Client-side navigation ( using useRouter hook )

### ISSUE THREAD

**Issue by Estifanos12** [TheSGJ/nextjs-toploader#34] opened 2023-07-31 07:00 UTC
Inside Client components when we use router.push('/someURL') the top loader finishes loading before the page entirely loads.

**Comment by TheSGJ** [comment] 2023-07-31 13:42
Closing this as it's a duplicate of  issue (#10). Watch (#10 ) for any solution or workaround.

**Closed by TheSGJ** 2023-07-31 13:42 UTC
Labels: duplicate
