### ISSUE TITLE
Gets stuck if href="#"

### ISSUE THREAD

**Issue by nabtron** [TheSGJ/nextjs-toploader#42] opened 2023-10-15 12:50 UTC
It should ignore if the href="#", instead gets stuck

**Comment by nabtron** [comment] 2023-10-15 14:21
can be solved by adding code after line 148.

Add after:
`          const newUrl = (anchor as HTMLAnchorElement).href;`

making it:
```
          const newUrl = (anchor as HTMLAnchorElement).href;
          if((newUrl.charAt(newUrl.length - 1)) == "#") return false;

```

**Comment by TheSGJ** [comment] 2024-02-07 09:51
Duplicate of #8

**Closed by TheSGJ** 2024-02-07 09:51 UTC
