### ISSUE TITLE
issue nextjs version 14.0.3 not finish loader

### ISSUE THREAD

**Issue by monir6163** [TheSGJ/nextjs-toploader#58] opened 2023-11-22 17:06 UTC
see screenshot: https://prnt.sc/7PcLZPeovabN

**Comment by Jings** [comment] 2023-11-23 08:12
Please see discussion in Issue #56 
It is known and caused by a behaviour change in the current NextJS 14.0.3 Release.

**Comment by netstermonir** [comment] 2023-11-23 08:17
yes, I see but why we are using the next js old version? You fix and update your package. thanks

**Comment by favfly-dev** [comment] 2023-12-04 09:12
Please fix this issue **ASAP**, I am facing problem with Next js Top loader after Next JS v14.0.3 upgrade. You need to fix this ASAP , otherwise, it would be breaking the production level website/applications

**Comment by Super-Kenil** [comment] 2023-12-09 10:54
@monir6163 This is an  DUPLICATE issue, refer to the first issue here #56 . Mark this as closed

The #56 issue is fixed in the new Nextjs v14.0.4

**Closed** 2023-12-14 06:17 UTC
