### ISSUE TITLE
So how is this supposed to work?

### ISSUE THREAD

**Issue by cjurjiu** [TheSGJ/nextjs-toploader#57] opened 2023-11-21 19:14 UTC
> A Next.js Top Loading Bar component made using nprogress, works with Next.js 14.

The readme describes what _this_ (a loading bar), what's it build on top of (nprogress), and that it also works with Nextjs. It also explains various config options, although some of them would imho need some more details (e.g. `crawlSpeed`?)

Yet is doesn't explain how it is _supposed_ to work. When does loading start? When should it stop? 

My experience is that I installed this in my project, I see the progress bar starting when I click to navigate to a new page yet the page loads but the progress bar is still only halfway done. I also checked the network tab, no requests are happening in the background, yet the loading bar is still there -> this is weird.

So then I can't help but think: is this indented? is it not? do I need to change some setting? I don't know, the readme doesn't get into these details.

If I _knew_ this info, I wouldn't mind making a PR where this kind of info is mentioned. Sadly I don't.

**Comment by njbmartin** [comment] 2023-11-22 02:32
There's a bug #56  caused by Next 14.0.3

**Comment by cjurjiu** [comment] 2023-11-22 11:14
Thanks @njbmartin, downgrading to 14.0.2 did the trick for me. 

But my point is still valid I would say: the docs feel written for someone that already knows how the library works. Take for instance `showSpinner` -> where is this spinner shown? I can't see any different with this option on or off.

 What does `crawl` mean? Docs say "auto incrementing behavior for the TopLoader.". Does it refer to the integer amount added to the width of the topbar on each tick/update? if yes, then `crawl` is a weird name.

etc.

**Comment by nunesunil** [comment] 2023-12-03 19:59
Fixed by https://github.com/vercel/next.js/pull/58861 and released in [v14.0.4-canary.37](https://github.com/vercel/next.js/commit/141dbb2663c2f7605df9a19af2ed5154e7b6c881).

**Closed** 2024-03-23 16:31 UTC
